# Generated by Django 4.2.6 on 2023-11-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_remove_worker_fields'),
        ('fields', '0002_remove_field_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='workers',
            field=models.ManyToManyField(null=True, to='workers.worker'),
        ),
    ]
