# Generated by Django 4.2.6 on 2023-11-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_field_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='workers',
            new_name='workersIds',
        ),
    ]
