# Generated by Django 4.2.6 on 2023-10-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='fields',
        ),
    ]
