version: '3'

services:
    web:
        image: choko2/nitko-api
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn backend.wsgi:application -b 0.0.0.0:8000
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - server

    db:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        env_file:
            - .env
        volumes:
            - ./postgresql:/var/lib/postgresql/data
        networks:
            - server

networks:
    server:
        driver: bridge

volumes:
    sqlite_data:
