# Generated by Django 4.2.6 on 2023-10-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('PLOWING', 'Оран'), ('CULTIVATIONG', 'Култивиране'), ('SPRAYING_WEEDS', 'Пръскане против треви'), ('SPRAYING_FUNGUS', 'Пръскане против гъбични инфекции'), ('SPRAYING_BUGS', 'Пръскане против буболечки'), ('FERTILIZING', 'Торене'), ('PLANTING', 'Сеитба'), ('HARVESTING', 'Жътва')], max_length=32)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fields.field')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workers.worker')),
            ],
        ),
    ]
