# Generated by Django 4.2.6 on 2023-10-21 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Оран', 'Оран'), ('Култивиране', 'Култивиране'), ('Пръскане против треви', 'Пръскане против треви'), ('Пръскане против гъбични инфекции', 'Пръскане против гъбични инфекции'), ('Пръскане против буболечки', 'Пръскане против буболечки'), ('Торене', 'Торене'), ('Сеитба', 'Сеитба'), ('Жътва', 'Жътва')], max_length=32),
        ),
    ]
