# Generated by Django 4.2.6 on 2023-11-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_remove_field_worker'),
        ('workers', '0003_remove_worker_fields'),
        ('jobs', '0002_job_created_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fields.field'),
        ),
        migrations.AlterField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker'),
        ),
    ]
